package com.evansitzes.vocabularyflashcards.model;

/**
 * Created by evan on 9/24/15.
 */
public class BasicChineseWords extends Flashcard {
    @Override
    public void populateInitialWordlist() {
        foreignToEnglish.put("愛", "to love/affection/to be fond of/to like - ài");
        foreignToEnglish.put("八", "eight/8 - bā");
        foreignToEnglish.put("杯子", "cup/glass/CL:個|个[ge4],支[zhi1],枝[zhi1] - bēi zi");
        foreignToEnglish.put("本", "roots or stems of plants/origin/source/this/the current/root/foundation/basis/(classifier for books, periodicals, files etc) - běn");
        foreignToEnglish.put("不", "(negative prefix)/not/no - bù");
        foreignToEnglish.put("不客气", "you're welcome/impolite/rude/blunt/don't mention it - bù kè qi");
        foreignToEnglish.put("菜", "dish (type of food)/vegetables/vegetable/cuisine/CL:盤|盘[pan2],道[dao4] - cài");
        foreignToEnglish.put("茶", "tea/tea plant/CL:杯[bei1],壺|壶[hu2] - chá");
        foreignToEnglish.put("吃", "to eat/to have one's meal/to eradicate/to destroy/to absorb/to suffer/to exhaust - chī");
        foreignToEnglish.put("出租车", "taxi - chū zū chē");
        foreignToEnglish.put("大", "big/huge/large/major/great/wide/deep/oldest/eldest - dà");
        foreignToEnglish.put("打电话", "to make a telephone call - dǎ diàn huà");
        foreignToEnglish.put("大", "doctor - dài");
        foreignToEnglish.put("的", "really and truly - dí");
        foreignToEnglish.put("的", "aim/clear - dì");
        foreignToEnglish.put("点", "point/dot/speck/drop/decimal point/point of a scale/point in a theory or argument/downwards-right convex character stroke/a little (usually 一點|一点)/a jot/beat (of percussion instrument)/to draw a dot/to touch slightly/to drip/classifier for items/classifier for small indeterminate quantities/to nod/to select item from a list/to order (food in a restaurant)/to count/o'clock/one fifth of a two hour watch (old)/hour/point of time/iron bell (used to mark time)/pastry/dimsum 點心|点心/CL:個|个[ge4] - diǎn");
        foreignToEnglish.put("电脑", "computer/CL:臺|台[tai2] - diàn nǎo");
        foreignToEnglish.put("电视", "television/TV/CL:臺|台[tai2],個|个[ge4] - diàn shì");
        foreignToEnglish.put("电影", "movie/film/CL:片[pian4],幕[mu4],場|场[chang3] - diàn yǐng");
        foreignToEnglish.put("东西", "east and west - dōng xī");
        foreignToEnglish.put("东西", "thing/stuff/person/CL:個|个[ge4],件[jian4] - dōng xi");
        foreignToEnglish.put("读", "comma/phrase marked by pause - dòu");
        foreignToEnglish.put("都", "all/both (if two things are involved)/entirely (due to) each/even/already - dōu");
        foreignToEnglish.put("读", "to read/to study/reading of word (i.e. pronunciation), similar to 拼音[pin1 yin1] - dú");
        foreignToEnglish.put("都", "capital city/metropolis/surname Du - dū");
        foreignToEnglish.put("对不起", "unworthy/to let down/I'm sorry/excuse me/pardon me/if you please/sorry? (please repeat) - duì bu qǐ");
        foreignToEnglish.put("多", "many/much/a lot of/numerous/multi- - duō");
        foreignToEnglish.put("多少", "number/amount/somewhat - duō shǎo");
        foreignToEnglish.put("多少", "how much/how many/which (number)/as much as - duō shao");
        foreignToEnglish.put("二", "two/2 - èr");
        foreignToEnglish.put("儿子", "son - ér zi");
        foreignToEnglish.put("饭馆", "restaurant/CL:家[jia1] - fàn guǎn");
        foreignToEnglish.put("飞机", "airplane/CL: 架[jia4] - fēi jī");
        foreignToEnglish.put("分钟", "minute - fēn zhōng");
        foreignToEnglish.put("高兴", "happy/glad/willing (to do sth)/in a cheerful mood - gāo xìng");
        foreignToEnglish.put("个", "individual/this/that/size/classifier for people or objects in general - gè");
        foreignToEnglish.put("工作", "job/work/construction/task/CL:個|个[ge4],份[fen4],項|项[xiang4] - gōng zuò");
        foreignToEnglish.put("狗", "dog/CL:隻|只[zhi1],條|条[tiao2] - gǒu");
        foreignToEnglish.put("汉语", "Chinese language/CL:門|门[men2] - hàn yǔ");
        foreignToEnglish.put("好", "good/well/proper/good to/easy to/very/so/(suffix indicating completion or readiness) - hǎo");
        foreignToEnglish.put("好", "to be fond of - hào");
        foreignToEnglish.put("和", "and/together with/with/sum/union/peace/harmony/surname He/Japanese related - hé");
        foreignToEnglish.put("和", "cap (a poem)/to respond in singing - hè");
        foreignToEnglish.put("喝", "to drink/(interj.) My goodness! - hē");
        foreignToEnglish.put("喝", "shout applause - hè");
        foreignToEnglish.put("很", "(adverb of degree)/quite/very/awfully - hěn");
        foreignToEnglish.put("后面", "rear/back/behind/later/afterwards - hòu mian");
        foreignToEnglish.put("和", "to complete a set in mahjong or playing cards - hú");
        foreignToEnglish.put("回", "to circle/to go back/to turn around/to answer/to return/to revolve/Hui ethnic group (Chinese Muslims)/time/classifier for acts of a play/section or chapter (of a classic book) - huí");
        foreignToEnglish.put("会", "can/be possible/be able to/will/to assemble/to meet/to gather/to see/union/group/association/CL:個|个[ge4] - huì");
        foreignToEnglish.put("和", "soft/warm - huó");
        foreignToEnglish.put("和", "to mix together/to blend - huò");
        foreignToEnglish.put("几", "almost/small table - jī");
        foreignToEnglish.put("几", "how much/how many/several/a few - jǐ");
        foreignToEnglish.put("家", "home/family/classifier for families or businesses/refers to the philosophical schools of pre-Han China/noun suffix for specialists in some activity such as musician or revolutionary, corresponds to English -ist, -er, -ary or -ian/surname Jia/CL:個|个[ge4] - jiā");
        foreignToEnglish.put("叫", "to call/to yell/to order/to ask/to be called - jiào");
        foreignToEnglish.put("今天", "today/at the present/now - jīn tiān");
        foreignToEnglish.put("九", "nine/9 - jiǔ");
        foreignToEnglish.put("开", "to open/to start/to turn on/to write out (a medical prescription)/to operate (vehicle)/abbr. for 開爾文|开尔文 degrees Kelvin - kāi");
        foreignToEnglish.put("看", "to look after/to take care of/to watch/to guard - kān");
        foreignToEnglish.put("看", "to see/to look at/to read/to watch/to consider/to regard as/to view as/to treat as/to judge/(after repeated verb) to give it a try/depending on (how you're judging)/to visit/to call on/to treat (an illness)/to look after/Watch out! (for a danger) - kàn");
        foreignToEnglish.put("看见", "to see/to catch sight of - kàn jiàn");
        foreignToEnglish.put("块", "lump (of earth)/chunk/piece/classifier for pieces of cloth, cake, soap etc/colloquial word for yuan (or other unit of currency such as Hong Kong or US dollar etc), usually as 塊錢|块钱 - kuài");
        foreignToEnglish.put("会", "to balance an account/accounting - kuài");
        foreignToEnglish.put("来", "to come/to arrive/to come round/ever since/next - lái");
        foreignToEnglish.put("老师", "teacher/CL:個|个[ge4],位[wei4] - lǎo shī");
        foreignToEnglish.put("冷", "cold - lěng");
        foreignToEnglish.put("里", "inside/internal/interior/lining/village/basic unit of city administration - lǐ");
        foreignToEnglish.put("里", "inside/internal/interior/lining/village/basic unit of city administration - lǐ");
        foreignToEnglish.put("里", "Chinese mile (approx. 0.5 km)/neighborhood/hometown/surname Li - lǐ");
        foreignToEnglish.put("了", "to know/to understand - liǎo");
        foreignToEnglish.put("了", "clear - liǎo");
        foreignToEnglish.put("了", "to look afar from a high place - liào");
        foreignToEnglish.put("零", "remnant/zero - líng");
        foreignToEnglish.put("六", "six/6 - liù");
        foreignToEnglish.put("吗", "see 嗎啡|吗啡, morphine - mǎ");
        foreignToEnglish.put("吗", "(question tag) - ma");
        foreignToEnglish.put("妈妈", "mama/mommy/mother/CL:個|个[ge4],位[wei4] - mā ma");
        foreignToEnglish.put("买", "buy - mǎi");
        foreignToEnglish.put("猫", "cat/CL:隻|只[zhi1] - māo");
        foreignToEnglish.put("没", "(negative prefix for verbs)/have not/not - méi");
        foreignToEnglish.put("没关系", "it doesn't matter - méi guān xi");
        foreignToEnglish.put("米饭", "(cooked) rice - mǐ fàn");
        foreignToEnglish.put("明天", "tomorrow - míng tiān");
        foreignToEnglish.put("名字", "name (of a person or thing)/CL:個|个[ge4] - míng zi");
        foreignToEnglish.put("没", "drowned/to end/to die/to inundate - mò");
        foreignToEnglish.put("哪", "how/which - nǎ");
        foreignToEnglish.put("哪", "(particle equivalent to 啊 after noun ending in -n) - na");
        foreignToEnglish.put("那", "variant of 哪/how/which - nǎ");
        foreignToEnglish.put("那", "that/those/commonly pr. nei4 before a classifier, esp. in Beijing - nà");
        foreignToEnglish.put("哪儿", "where?/wherever/anywhere - nǎr");
        foreignToEnglish.put("那儿", "there - nàr");
        foreignToEnglish.put("呢", "(question particle for subjects already mentioned) - ne");
        foreignToEnglish.put("哪", "which? (interrogative, followed by classifier or numeral-classifier) - něi");
        foreignToEnglish.put("能", "can/may/capable/energy/able/surname Neng - néng");
        foreignToEnglish.put("你", "you (informal, as opposed to polite 您[nin2]) - nǐ");
        foreignToEnglish.put("呢", "woolen material - ní");
        foreignToEnglish.put("年", "year/CL:個|个[ge4] - nián");
        foreignToEnglish.put("女儿", "daughter - nǚ ér");
        foreignToEnglish.put("朋友", "friend/CL:個|个[ge4],位[wei4] - péng you");
        foreignToEnglish.put("漂亮", "pretty/beautiful - piào liang");
        foreignToEnglish.put("苹果", "apple/CL:個|个[ge4],顆|颗[ke1] - píng guǒ");
        foreignToEnglish.put("钱", "coin/money/surname Qian/CL:筆|笔[bi3] - qián");
        foreignToEnglish.put("前面", "ahead/in front/preceding/above - qián miàn");
        foreignToEnglish.put("请", "to ask/to invite/please (do sth)/to treat (to a meal etc)/to request - qǐng");
        foreignToEnglish.put("去", "to go/to leave/to remove/fourth tone of putonghua - qù");
        foreignToEnglish.put("热", "heat/to heat up/fervent/hot (of weather)/warm up - rè");
        foreignToEnglish.put("人", "man/person/people/CL:個|个[ge4],位[wei4] - rén");
        foreignToEnglish.put("认识", "to know/to recognize/to be familiar with/acquainted with sth/knowledge/understanding/awareness/cognition - rèn shi");
        foreignToEnglish.put("日", "day/sun/date/day of the month/abbr. for Japan/CL:個|个[ge4] - rì");
        foreignToEnglish.put("三", "three/3 - sān");
        foreignToEnglish.put("上", "on/on top/upon/first (of two parts)/previous or last (week etc)/upper/higher/above/previous/to climb/to go into/to go up/to attend (class or university)/third tone of putonghua - shàng");
        foreignToEnglish.put("商店", "store/shop/CL:家[jia1],個|个[ge4] - shāng diàn");
        foreignToEnglish.put("上午", "morning/CL:個|个[ge4] - shàng wǔ");
        foreignToEnglish.put("少", "few/little/lack - shǎo");
        foreignToEnglish.put("少", "young - shào");
        foreignToEnglish.put("谁", "who/also pronounced shui2 - shéi");
        foreignToEnglish.put("什么", "what/what?/who?/something/anything - shén me");
        foreignToEnglish.put("十", "ten/10 - shí");
        foreignToEnglish.put("是", "is/are/am/yes/to be - shì");
        foreignToEnglish.put("时候", "time/length of time/moment/period - shí hou");
        foreignToEnglish.put("书", "book/letter/same as 書經|书经 Book of History/CL:本[ben3],冊|册[ce4],部[bu4],叢|丛[cong2] - shū");
        foreignToEnglish.put("水", "water/river/surname Shui/CL:杯[bei1],筒[tong3],瓶[ping2] - shuǐ");
        foreignToEnglish.put("水果", "fruit/CL:個|个[ge4] - shuǐ guǒ");
        foreignToEnglish.put("睡觉", "to go to bed/to go to sleep - shuì jiào");
        foreignToEnglish.put("说话", "to speak/to say/to talk/to gossip/to tell stories/talk/word - shuō huà");
        foreignToEnglish.put("四", "four/4 - sì");
        foreignToEnglish.put("岁", "year/years old/classifier for years old - suì");
        foreignToEnglish.put("他", "he/him - tā");
        foreignToEnglish.put("她", "she - tā");
        foreignToEnglish.put("太", "highest/greatest/too (much)/very/extremely - tài");
        foreignToEnglish.put("天气", "weather - tiān qì");
        foreignToEnglish.put("听", "to listen/to hear/to obey/a can (loan from English tin)/classifier for canned beverages - tīng");
        foreignToEnglish.put("听", "to let/to allow - tìng");
        foreignToEnglish.put("同学", "(fellow) classmate/CL:位[wei4],個|个[ge4] - tóng xué");
        foreignToEnglish.put("喂", "hello (interj., esp. on telephone)/hey/to feed (sb or some animal) - wèi");
        foreignToEnglish.put("喂", "to feed - wèi");
        foreignToEnglish.put("我们", "we/us/ourselves/our - wǒ men");
        foreignToEnglish.put("喜欢", "to like/to be fond of - xǐ huan");
        foreignToEnglish.put("下", "down/downwards/below/lower/later/next (week etc)/second (of two parts)/to decline/to go down - xià");
        foreignToEnglish.put("下午", "afternoon/p.m./CL:個|个[ge4] - xià wǔ");
        foreignToEnglish.put("下雨", "rainy - xià yǔ");
        foreignToEnglish.put("先生", "sir/mister/teacher/(title of respect)/CL:個|个[ge4],位[wei4] - xiān sheng");
        foreignToEnglish.put("现在", "now/at present/modern/current/nowadays/at the moment/as of now - xiàn zài");
        foreignToEnglish.put("想", "to think/to believe/to suppose/to wish/to want/to miss - xiǎng");
        foreignToEnglish.put("小", "small/tiny/few/young - xiǎo");
        foreignToEnglish.put("小姐", "young lady/miss/CL:個|个[ge4],位[wei4] - xiǎo jie");
        foreignToEnglish.put("些", "some/few/several/(a measure word) - xiē");
        foreignToEnglish.put("写", "to write - xiě");
        foreignToEnglish.put("谢谢", "to thank/thanks - xiè xie");
        foreignToEnglish.put("星期", "week/CL:個|个[ge4] - xīng qī");
        foreignToEnglish.put("学习", "to learn/to study - xué xí");
        foreignToEnglish.put("学校", "school/CL:所[suo3] - xué xiào");
        foreignToEnglish.put("一", "one/1/single/a (article)/as soon as/entire/whole/all/throughout - yī");
        foreignToEnglish.put("衣服", "clothes/CL:件[jian4],套[tao4] - yī fu");
        foreignToEnglish.put("医生", "doctor/CL:個|个[ge4],位[wei4],名[ming2] - yī shēng");
        foreignToEnglish.put("医院", "hospital/CL:所[suo3],家[jia1],座[zuo4] - yī yuàn");
        foreignToEnglish.put("椅子", "chair/CL:把[ba3],套[tao4] - yǐ zi");
        foreignToEnglish.put("有", "to have/there is/there are/to exist/to be - yǒu");
        foreignToEnglish.put("月", "moon/month/CL:個|个[ge4],輪|轮[lun2] - yuè");
        foreignToEnglish.put("在", "(located) at/(to be) in/to exist/in the middle of doing sth/(indicating an action in progress) - zài");
        foreignToEnglish.put("再见", "goodbye/see you again later - zài jiàn");
        foreignToEnglish.put("怎么", "how?/what?/why? - zěn me");
        foreignToEnglish.put("怎么样", "how?/how about?/how was it?/how are things? - zěn me yàng");
        foreignToEnglish.put("这", "this/these/(commonly pronounced zhei4 before a classifier, esp. in Beijing) - zhè");
        foreignToEnglish.put("这儿", "here - zhèr");
        foreignToEnglish.put("中国", "China/Middle Kingdom - zhōng guó");
        foreignToEnglish.put("中午", "noon/midday/CL:個|个[ge4] - zhōng wǔ");
        foreignToEnglish.put("住", "to live/to dwell/to stay/to reside/to stop - zhù");
        foreignToEnglish.put("桌子", "table/desk/CL:張|张[zhang1],套[tao4] - zhuō zi");
        foreignToEnglish.put("字", "letter/symbol/character/word/CL:個|个[ge4] - zì");
        foreignToEnglish.put("做", "to do/to make/to produce/to write/to compose/to act as/to engage in/to hold (a party)/to be/to become/to function (in some capacity)/to serve as/to be used for/to form (a bond or relationship)/to pretend/to feign/to act a part/to put on appearance - zuò");
        foreignToEnglish.put("坐", "to sit/to take a seat/to take (a bus, airplane etc)/to bear fruit/surname Zuo - zuò");
        foreignToEnglish.put("昨天", "yesterday - zuó tiān");
    }
}
