package com.evansitzes.vocabularyflashcards.model;

/**
 * Created by evan on 9/24/15.
 */
public class KanjiJapanese extends Flashcard {
    @Override
    public void populateInitialWordlist() {
        foreignToEnglish.put("訪問", "ほうもん　a visit");
        foreignToEnglish.put("禁止", "きんし　prohibition");
        foreignToEnglish.put("禁煙", "きんえん　no smoking");
        foreignToEnglish.put("安政", "あんせい　quiet (静か）");
        foreignToEnglish.put("危機", "きき　crisis （危ない）");
        foreignToEnglish.put("危険", "きけん　danger");
        foreignToEnglish.put("落第", "らくだい　failing a course （落とす）");
        foreignToEnglish.put("駐車場", "ちゅうしゃじょう　parking lot");
        foreignToEnglish.put("捨てる", "すてる　throw away");
        foreignToEnglish.put("遊泳", "ゆうえい　swimming");
        foreignToEnglish.put("喫煙所", "きつえんじょ　smoking room");
        foreignToEnglish.put("喫茶店", "きっさてん　cafe");
        foreignToEnglish.put("受験", "じゅけん　taking a test");
        foreignToEnglish.put("案内", "あんない");
        foreignToEnglish.put("議論", "ぎろん　debate");
        foreignToEnglish.put("化学", "かがく　chemistry");
        foreignToEnglish.put("階段", "かいだん　staircase");
        foreignToEnglish.put("段階", "だんかい　level");
        foreignToEnglish.put("営業", "えいぎょう　business");
        foreignToEnglish.put("放送", "ほうそう　broadcast");
        foreignToEnglish.put("放す", "はなす　to let go");
        foreignToEnglish.put("水準", "すいじゅん　a standard");
        foreignToEnglish.put("備え付け", "そなえつけ　furnished with X");
        foreignToEnglish.put("清掃", "せいそう　cleaning");
        foreignToEnglish.put("清い", "きよい　clean/pure");
        foreignToEnglish.put("欠点", "けってん　shortcoming");
        foreignToEnglish.put("点検", "てんけん　inspection");
        foreignToEnglish.put("検定", "けんてい　official certification");
        foreignToEnglish.put("窓口", "まどぐち　service window");
        foreignToEnglish.put("精神", "せいしん　spirit, mind");
        foreignToEnglish.put("計算", "けいさん　a calculation");
        foreignToEnglish.put("引き算", "ひきざん　a subtraction");
        foreignToEnglish.put("足し算", "たしざん　an addition");
        foreignToEnglish.put("改正", "かいせい　an amendment, revision");
        foreignToEnglish.put("改札口", "かいさつぐち　ticket gate");
        foreignToEnglish.put("下線", "かせん　an underline");
        foreignToEnglish.put("快速", "かいそく　high speed");
        foreignToEnglish.put("早速", "さっそく　at once");
        foreignToEnglish.put("道路", "どうろ　a road");
        foreignToEnglish.put("通路", "つうろ an aisle");
        foreignToEnglish.put("軽油", "けいゆ via X");
        foreignToEnglish.put("深刻", "しんこく　serious");
        foreignToEnglish.put("深い", "ふかい");
        foreignToEnglish.put("下降", "かこう　a descent (降りる）");
        foreignToEnglish.put("両替え", "りょうかえ　money exchange");
        foreignToEnglish.put("家賃", "やちん");
        foreignToEnglish.put("運賃", "うんちん　fare");
        foreignToEnglish.put("増加", "ぞうか　an increase");
        foreignToEnglish.put("割増", "わりまし　an extra, a proportional increase");
        foreignToEnglish.put("優先", "ゆうせん priority (seating)");
        foreignToEnglish.put("側面", "そくめん the sides/flanks");
        foreignToEnglish.put("寄る", "よる　stop by");
        foreignToEnglish.put("郵便", "ゆうびん　post");
        foreignToEnglish.put("郵送", "ゆうそう　sending by mail");
        foreignToEnglish.put("貯金", "ちょきん　savings");
        foreignToEnglish.put("包む", "つつむ　to wrap");
        foreignToEnglish.put("包帯", "ほうたい　bandage");
        foreignToEnglish.put("発達", "はったつ　development");
        foreignToEnglish.put("実際に", "じっさいに　actually");
        foreignToEnglish.put("初恋", "はつこい　ones first love");
        foreignToEnglish.put("初雪", "はつゆき　first snow");
        foreignToEnglish.put("再生", "さいせい　regeneration");
        foreignToEnglish.put("診療", "しんりょう medical exam and treatment");
        foreignToEnglish.put("科学", "かがく　science");
        foreignToEnglish.put("主婦", "しゅふ　a housewife");
        foreignToEnglish.put("皮肉", "ひにく　irony, sarcasm");
        foreignToEnglish.put("救急", "きゅうきゅう　first aid");
        foreignToEnglish.put("看板", "かんばん　a board");
        foreignToEnglish.put("案内板", "あんないばん　notice board");
        foreignToEnglish.put("成人式", "せいじんしき coming of age ceremony");
        foreignToEnglish.put("総合病院", "そうごうびょういん　general hospital");
        foreignToEnglish.put("総計", "そうけい　the total");
        foreignToEnglish.put("発券", "はっけん　issuing of a ticket");
        foreignToEnglish.put("危機", "きき　a crisis");
        foreignToEnglish.put("回復", "かいふく　recovery");
        foreignToEnglish.put("片道切符", "かたみちきっぷ　one-way ticket");
        foreignToEnglish.put("片付ける", "かたづける　tidying up");
        foreignToEnglish.put("定期券", "ていきけん　commuters pass");
        foreignToEnglish.put("調整", "ちょうせい　an adjustment");
        foreignToEnglish.put("調子", "ちょうし　condition");
        foreignToEnglish.put("整備", "せいび　mainenance, overhall");
        foreignToEnglish.put("発表", "はっぴょう　announcement");
        foreignToEnglish.put("表面", "ひょうめん　area");
        foreignToEnglish.put("表示", "ひょうじ expression, indication");
        foreignToEnglish.put("現金", "げんきん　cash");
        foreignToEnglish.put("支持", "しじ　support");
        foreignToEnglish.put("支店", "してん　support/branch office");
        foreignToEnglish.put("預金", "よきん　a deposit");
        foreignToEnglish.put("預ける", "あずける　entrust (預かる)");
        foreignToEnglish.put("払い戻し", "はらいもどし　a deposit");
        foreignToEnglish.put("残る", "のこる　left behind");
        foreignToEnglish.put("対照的", "たいしょうてき　being contrastive");
        foreignToEnglish.put("照らす", "てらす　to light up");
        foreignToEnglish.put("硬い", "かたい　hard");
        foreignToEnglish.put("貨物", "かもつ　freight");
        foreignToEnglish.put("通貨", "つうか　currency");
        foreignToEnglish.put("確か", "たしかに");
        foreignToEnglish.put("明確", "めいかく　clear");
        foreignToEnglish.put("認める", "みとめる　to admit/approve");
        foreignToEnglish.put("違法", "いほう　illegal");
        foreignToEnglish.put("取り消す", "とりけす　a cancellation");
        foreignToEnglish.put("消去", "しょうきょ　elimination");
        foreignToEnglish.put("温室", "おんしつ　greenhouse");
        foreignToEnglish.put("新緑", "しんりょく　fresh greenery");
        foreignToEnglish.put("玉", "たま　a ball/sphere");
        foreignToEnglish.put("返金", "へんきん　 a refund");
        foreignToEnglish.put("返す", "かえす");
        foreignToEnglish.put("集団", "しゅうだん　group");
        foreignToEnglish.put("一般", "いっぱん　in general");
        foreignToEnglish.put("幼児", "ようじ　a baby");
        foreignToEnglish.put("未定", "みてい　undecided, uncertain");
        foreignToEnglish.put("未来", "みらい　future");
        foreignToEnglish.put("未知", "みち　unknown");
        foreignToEnglish.put("満足", "まんぞく　satisfaction");
        foreignToEnglish.put("老人", "ろうじん　old person");
        foreignToEnglish.put("設定", "せってい　setting");
        foreignToEnglish.put("乗り換える", "のりかえる");
        foreignToEnglish.put("停止", "ていし　stopping");
        foreignToEnglish.put("停電", "ていでん　electric blackout");
        foreignToEnglish.put("掃除", "そうじ　cleaning");
        foreignToEnglish.put("湿度", "しつど　humidity");
        foreignToEnglish.put("チャラマーカス", "charai marcus");
        foreignToEnglish.put("標準", "ひょうじゅん　a standard");
        foreignToEnglish.put("標本", "ひょうほん　a specimen, sample");
        foreignToEnglish.put("巻き戻る", "まきもどる　rewind (巻く　= to roll)");
        foreignToEnglish.put("予習", "よしゅう　planning (of a lesson)");
        foreignToEnglish.put("予備", "よび　a reserve/spare");
        foreignToEnglish.put("保険", "ほけん　insurance");
        foreignToEnglish.put("保守的", "ほしゅてき　conservative, retaining and protecting");
        foreignToEnglish.put("済む", "すむ　to be finished, completed");
        foreignToEnglish.put("事件", "じけん　incident, crime");
        foreignToEnglish.put("通信", "つうしん　correspondence");
        foreignToEnglish.put("履歴書", "りれきしょ　resume");
        foreignToEnglish.put("受信箱", "じゅしんばこ　inbox （送信箱　そうしんばこ）");
        foreignToEnglish.put("規定", "きてい　regulation");
        foreignToEnglish.put("変換", "へんかん　conversion");
        foreignToEnglish.put("選択肢", "せんたくし　alternatives, selections");
        foreignToEnglish.put("登録", "とうろく");
        foreignToEnglish.put("修正", "しゅうせい　amendment");
        foreignToEnglish.put("修理", "しゅうり　repairs/ fixing");
        foreignToEnglish.put("完成", "かんせい　completion, accomplishment");
        foreignToEnglish.put("終了", "しゅうりょう　end, completion （終了・しゅうりょう　completion of a course)");
        foreignToEnglish.put("画像", "がぞう　picture/image");
        foreignToEnglish.put("映像", "えいぞう　reflection, image, video");
        foreignToEnglish.put("人類", "じんるい　human race");
        foreignToEnglish.put("中央", "ちゅうおう　center");
        foreignToEnglish.put("保存", "ほぞん　preserve, store");
        foreignToEnglish.put("存在", "そんざい　existance");
        foreignToEnglish.put("印刷", "いんさつ　printing");
        foreignToEnglish.put("拡大", "かくだい　enlargement");
        foreignToEnglish.put("縮小", "しゅくしょう　reduction");
        foreignToEnglish.put("同様", "どうよう　the same");
        foreignToEnglish.put("要約", "ようやく　a summary");
        foreignToEnglish.put("要点", "ようてん　an essential point");
        foreignToEnglish.put("金利", "きんり　interest (rate)");
        foreignToEnglish.put("明細", "めいさい　detail （細かい・こまかい）");
        foreignToEnglish.put("在沖", "ざいちゅう　containing");
        foreignToEnglish.put("関連", "かんれん　(relationship)");
        foreignToEnglish.put("連絡", "れんらく　");
        foreignToEnglish.put("入荷", "にゅうか　(receipt of goods");
        foreignToEnglish.put("届ける", "とどける　(to deliver)");
        foreignToEnglish.put("衣食住", "いしょくじゅう　(food/clothing/shelter)");
        foreignToEnglish.put("他方", "たほう　((on) the other hand)");
        foreignToEnglish.put("内臓", "ないぞう　(contained withing, organs)");
        foreignToEnglish.put("冷蔵", "れいぞう　(refrigeration)");
        foreignToEnglish.put("凍る", "こおる　to freeze");
        foreignToEnglish.put("等", "など");
        foreignToEnglish.put("配る", "くばる　to distribute");
        foreignToEnglish.put("担当", "たんとう　tanking charge");
        foreignToEnglish.put("当日", "とうじつ　that day");
        foreignToEnglish.put("頂点", "ちょうてん　apex, summit");
        foreignToEnglish.put("商業", "しょうぎょう　commerce");
        foreignToEnglish.put("個別", "こべつ　individual, separate");
        foreignToEnglish.put("交流", "こうりゅう　an exchange");
        foreignToEnglish.put("有効", "ゆうこう　valid (効果）");
        foreignToEnglish.put("限界", "けんがい　a limit (門限，期限）");
        foreignToEnglish.put("完全", "かんぜん　(perfect/complete)");
        foreignToEnglish.put("～と共に", "とともに　together with");
        foreignToEnglish.put("忘年会", "ぼうねんかい　party at the end of the year");
        foreignToEnglish.put("経過", "けいか　a process/course");
        foreignToEnglish.put("経理", "けいり　accounting");
        foreignToEnglish.put("過去", "かこ　the past");
        foreignToEnglish.put("責任", "せきにん");
        foreignToEnglish.put("任せる", "まかせる　to entrust");
        foreignToEnglish.put("負担", "ふたん　a burden");
        foreignToEnglish.put("袋", "ぶくろ　bag (plastic)");
        foreignToEnglish.put("集積場", "しゅうせきじょう　collection point (ゴミ)");
        foreignToEnglish.put("面積", "めんせき　surface area");
        foreignToEnglish.put("積もる", "つもる　to pile up");
        foreignToEnglish.put("燃料", "ねんりょう　fuel");
        foreignToEnglish.put("紅葉", "こうよう　changing of leaves");
        foreignToEnglish.put("葉", "は　a leaf");
        foreignToEnglish.put("容器", "ようき　a container");
        foreignToEnglish.put("楽器", "がっき　a musical instrument");
        foreignToEnglish.put("新装開店", "しんそうかいてん　rennovated and reopened");
        foreignToEnglish.put("包装", "ほうそう　wrapping");
        foreignToEnglish.put("雑", "ざつ　miscellaneous");
        foreignToEnglish.put("雑誌", "ざっし　a journal (日誌)");
        foreignToEnglish.put("資源", "しげん　resources");
        foreignToEnglish.put("資料", "しりょう　materials/data");
        foreignToEnglish.put("tesuto", "testing");
        foreignToEnglish.put("困難", "こんなん　difficult");
        foreignToEnglish.put("訓練", "くんれん　training/ a drill （練習）");
        foreignToEnglish.put("震える", "ふるえる　to tremble/shake");
        foreignToEnglish.put("加速", "かそく　acceleration (参加）");
        foreignToEnglish.put("延長", "えんちょう　an extension");
        foreignToEnglish.put("延期", "えんき　a postponement");
        foreignToEnglish.put("断水", "だんすい　suspension of water supply");
        foreignToEnglish.put("迷惑", "めいわく　a nuisance");
        foreignToEnglish.put("迷信", "めいしん　a superstition");
        foreignToEnglish.put("平気", "へいき　calm, indifferent");
        foreignToEnglish.put("結果", "けっか　a result");
        foreignToEnglish.put("果物", "くだもの　fruit");
        foreignToEnglish.put("各地", "かくち　everywhere/many places");
        foreignToEnglish.put("地位", "ちい　status");
        foreignToEnglish.put("異常", "いじょう　abnormal");
        foreignToEnglish.put("異なる", "ことなる　differ");
        foreignToEnglish.put("移動", "いどう　a move/transfer");
        foreignToEnglish.put("事務", "じむ　office work");
        foreignToEnglish.put("任務", "にんむ　a duty/task");
        foreignToEnglish.put("更新", "こうしん　renewal, update");
        foreignToEnglish.put("乗り越す", "のりこす　go past (the correct station)");
        foreignToEnglish.put("郊外", "こうがい　the suberbs");
        foreignToEnglish.put("円周", "えんしゅう　circumference");
        foreignToEnglish.put("畑", "はたけ　field");
        foreignToEnglish.put("中毒", "ちゅうどく　addiction");
        foreignToEnglish.put("依頼", "いらい　request/commission");
        foreignToEnglish.put("信頼", "しんらい　trust");
        foreignToEnglish.put("到着", "とうちゃく　arrival");
        foreignToEnglish.put("失望", "しつぼう　loss of hope/despair");
        foreignToEnglish.put("申請", "しんせい　an application");
        foreignToEnglish.put("姓名", "せいめい　full name");
        foreignToEnglish.put("住宅", "じゅうたく　housing");
        foreignToEnglish.put("勤務", "きんむ　service/duty");
        foreignToEnglish.put("通勤", "つうきん　commuting to work");
        foreignToEnglish.put("学部", "がくぶ　a department/faculty");
        foreignToEnglish.put("婚約", "こんやく　engagement");
        foreignToEnglish.put("未婚", "みこん　no marriage");
        foreignToEnglish.put("招待", "しょうたい　an invitation");
        foreignToEnglish.put("欠点", "けってん　a shortcoming");
        foreignToEnglish.put("政治", "せいじ　politics");
        foreignToEnglish.put("自治会", "じちかい　a self governing body");
        foreignToEnglish.put("委員会", "いいんかい　a comittee");
        foreignToEnglish.put("委任状", "いにんじょう　power of attourney");
        foreignToEnglish.put("祝日", "しゅくじつ　a holiday");
        foreignToEnglish.put("失礼", "しつれい　rude");
        foreignToEnglish.put("多忙", "たぼう　busy (with many things)");
        foreignToEnglish.put("出張", "しゅっちょう　a business trip");
        foreignToEnglish.put("浅い", "あさい　shallow");
        foreignToEnglish.put("永久", "えいきゅう　eternity");
        foreignToEnglish.put("総合", "そうごう　synthesis, cordination");
        foreignToEnglish.put("相互", "そうご　mutual/reciprocial");
        foreignToEnglish.put("追い越す", "おいこす　to overtake");
        foreignToEnglish.put("お歳暮", "おせいぼ　a year end gift");
        foreignToEnglish.put("習慣", "しゅうかん　custom/habit");
        foreignToEnglish.put("活用", "かつよう　practical use");
        foreignToEnglish.put("健康", "けんこう　health");
        foreignToEnglish.put("福祉", "ふくし　welfare");
        foreignToEnglish.put("打ち合わせ", "うちあわせ　to arrange in advance");
        foreignToEnglish.put("幸運", "こううん　lucky");
        foreignToEnglish.put("失業", "しつぎょう　unemployment");
        foreignToEnglish.put("突然", "とつぜん　sudden");
        foreignToEnglish.put("天然", "てんねん　natural/unartificial");
        foreignToEnglish.put("諸問題", "しょもんだい　varioius problems");
        foreignToEnglish.put("事情", "じじょう circumstances");
        foreignToEnglish.put("引退", "いんたい　retirement");
        foreignToEnglish.put("退職", "たいしょく　retirement");
        foreignToEnglish.put("介入", "かいにゅう an intervention");
        foreignToEnglish.put("一次試験", "いちじしけん　first test");
        foreignToEnglish.put("章", "しょう　chapter");
        foreignToEnglish.put("適度", "てきど　moderate");
        foreignToEnglish.put("誤解", "ごかい　a misunderstanding");
        foreignToEnglish.put("直線", "ちょくせん　 a straight line");
        foreignToEnglish.put("例外", "れいがい　an exception");
        foreignToEnglish.put("形式", "けいしき　form/format");
        foreignToEnglish.put("図形", "ずけい　diagram");
        foreignToEnglish.put("助手", "じょしゅ　an assistant");
        foreignToEnglish.put("助詞", "じょし　a partical");
        foreignToEnglish.put("副詞", "ふくし　an adverb");
        foreignToEnglish.put("夢中", "むちゅう　to be engrossed");
        foreignToEnglish.put("専用", "せんよう　eclusive use");
        foreignToEnglish.put("地域", "ちいき　area/region");
        foreignToEnglish.put("検査", "けんさ　an inspection/test");
        foreignToEnglish.put("調査", "ちょうさ　an investigation/inquiry");
        foreignToEnglish.put("大戦", "たいせん　a major war");
        foreignToEnglish.put("将来", "しょうらい　future");
        foreignToEnglish.put("憎い", "にくい　detestable");
        foreignToEnglish.put("悲観", "ひかん　pessimism");
        foreignToEnglish.put("感情", "かんじょう　emotion");
        foreignToEnglish.put("地球", "ちきゅう　the earth");
        foreignToEnglish.put("改良", "かいりょう　improvement/reform");
        foreignToEnglish.put("腹痛", "ふくつう　a stomache");
        foreignToEnglish.put("吸収", "きゅうしゅう　absorbtion");
        foreignToEnglish.put("傾向", "けいこう　tendency");
        foreignToEnglish.put("恐れ", "おそれ　fear/risk");
        foreignToEnglish.put("原料", "げんりょう　raw material");
        foreignToEnglish.put("原産", "げんさん　origin, indigenous");
        foreignToEnglish.put("要因", "よういん　a factor");
        foreignToEnglish.put("昼寝", "ひるね　a nap");
        foreignToEnglish.put("燃焼", "ねんしょう　combustion");
        foreignToEnglish.put("接触", "せっしょく　contact");
        foreignToEnglish.put("石油", "せきゆ　petroleum");
        foreignToEnglish.put("原油", "げんゆ　crude oil");
        foreignToEnglish.put("余計", "よけい　excessive/needless");
        foreignToEnglish.put("結局", "けっきょく　in the end, finally");
        foreignToEnglish.put("毛皮", "けがわ　fur");
        foreignToEnglish.put("肌着", "はだぎ　undershirt, \"Skin shirt\"");
        foreignToEnglish.put("柔軟", "じゅうなん　flexible");
        foreignToEnglish.put("香水", "こうすい　perfume");
        foreignToEnglish.put("柔軟体操", "じゅうなんたいそう　warm up exercise");
        foreignToEnglish.put("溶ける", "とける　to dissolve/melt (溶かす)");
        foreignToEnglish.put("洗濯", "せんたく　cleaning");
        foreignToEnglish.put("直接", "ちょくせつ　direct");
        foreignToEnglish.put("間接", "かんせつ　indirect");
        foreignToEnglish.put("接近", "せっきん　proximity");
        foreignToEnglish.put("泥棒", "どろぼう　theif (泥　= mud)");
        foreignToEnglish.put("黄色", "きいろ　yellow");
        foreignToEnglish.put("途中", "とちゅう　on the way");
        foreignToEnglish.put("家具", "かぐ　furniture");
        foreignToEnglish.put("床", "ゆか　floor");
        foreignToEnglish.put("壁", "かべ　wall");
        foreignToEnglish.put("乾く", "かわく　to be dry (乾かす)");
        foreignToEnglish.put("分布", "ぶんぷ　distribution, range");
        foreignToEnglish.put("柱", "はしら　pillar");
        foreignToEnglish.put("歯科", "しか　dentistry");
        foreignToEnglish.put("予防", "よぼう　prevention, precaution");
        foreignToEnglish.put("防止", "ぼうし　prevention");
        foreignToEnglish.put("磨く", "みがく　polish, brush");
        foreignToEnglish.put("追い抜く", "おいぬく　to be left behind");
        foreignToEnglish.put("悩む", "なやむ　to be worried about");
        foreignToEnglish.put("髪", "かみ　hair");
        foreignToEnglish.put("名刺", "めいし　namecard");
        foreignToEnglish.put("刺激", "しげき　a stimulus, excitement, motivation");
        foreignToEnglish.put("肩", "かた　shoulder");
        foreignToEnglish.put("節約", "せつやく　thrift");
        foreignToEnglish.put("調節", "ちょうせつ　an adjustment");
        foreignToEnglish.put("神経", "しんけい　a nerve");
        foreignToEnglish.put("神話", "しんわ　 a myth");
        foreignToEnglish.put("入浴", "にゅうよく　bathing");
        foreignToEnglish.put("的確", "てきかく　accurate, precise");
        foreignToEnglish.put("汗", "あせ　sweat");
        foreignToEnglish.put("会談", "かいだん　a conference");
        foreignToEnglish.put("折れる", "おれる　break (折る = to break something)");
        foreignToEnglish.put("賞金", "しょうきん　prize money");
        foreignToEnglish.put("賞味期限", "しょうみきげん　best before date");
        foreignToEnglish.put("金庫", "きんこ　a safe");
        foreignToEnglish.put("車庫", "しゃこ　a garage");
        foreignToEnglish.put("冷蔵庫", "れぞうこ　fridge");
        foreignToEnglish.put("製造", "せいぞう　manufacturing");
        foreignToEnglish.put("改造", "かいぞう　reconstruction, remodeling, reorganization");
        foreignToEnglish.put("費用", "ひよう　cost");
        foreignToEnglish.put("消費", "しょうひ　consumption");
        foreignToEnglish.put("可決", "かけつ　agreement, passage (of a bill)");
        foreignToEnglish.put("秒", "びょう　a second");
        foreignToEnglish.put("身長", "しんちょう　height");
        foreignToEnglish.put("召し上がる", "めしあがる　to eat (humble)");
        foreignToEnglish.put("湧く", "わく　to boil (沸かす　boil something)");
        foreignToEnglish.put("花粉", "かふん　pollen");
        foreignToEnglish.put("末", "すえ　the last, final");
        foreignToEnglish.put("栄養", "えいよう　nutrition");
        foreignToEnglish.put("訪れる", "おとずれる　to visit, come　(intransitive)");
        foreignToEnglish.put("訪ねる", "たずねる　to visit (transitive)");
        foreignToEnglish.put("呼吸", "こきゅう　breath, respiration");
        foreignToEnglish.put("呼び出す", "よびだす　to call, summon");
        foreignToEnglish.put("警察", "けいさつ　police");
        foreignToEnglish.put("警備", "けいび　security");
        foreignToEnglish.put("情報", "じょうほう　information");
        foreignToEnglish.put("予報", "よほう　a forcast");
        foreignToEnglish.put("裏切る", "うらぎる　to betray");
        foreignToEnglish.put("交差点", "こうさてん　a crossroads");
        foreignToEnglish.put("差", "さ　difference");
        foreignToEnglish.put("差別", "さべつ　discrimination");
        foreignToEnglish.put("手続き", "てつづき　procedure");
        foreignToEnglish.put("辞める", "やめる　to quit, resign");
        foreignToEnglish.put("画面", "がめん　screen");
        foreignToEnglish.put("方面", "ほうめん　direction");
        foreignToEnglish.put("面接", "めんせつ　surface area");
        foreignToEnglish.put("操作", "そうさ　operate, navigate, manipulate");
        foreignToEnglish.put("体操", "たいそう　exercise, gymnastics");
        foreignToEnglish.put("事実", "じじつ　a fact");
        foreignToEnglish.put("実験", "じっけん　an experiment");
        foreignToEnglish.put("列島", "れっとう　an archipegalo");
        foreignToEnglish.put("得", "とく　profit");
        foreignToEnglish.put("納得", "なっとく　assent, understanding");
        foreignToEnglish.put("広告", "こうこく　an advertisement");
        foreignToEnglish.put("警告", "けいこく　a warning, caution");
        foreignToEnglish.put("報告", "ほうこく　a report");
        foreignToEnglish.put("精勤", "せいきん　a tax");
        foreignToEnglish.put("税関", "ぜいかん　customs");
        foreignToEnglish.put("消費税", "しょうひぜい　consumption tax");
        foreignToEnglish.put("定価", "ていか　a fixed price");
        foreignToEnglish.put("性格", "せいかく　character, personality");
        foreignToEnglish.put("超過", "ちょうか　excess, overrun, surplus");
        foreignToEnglish.put("均等", "きんとう　uniformity, equality");
        foreignToEnglish.put("長靴", "ながぐつ　boots");
        foreignToEnglish.put("印象", "いんしょう　an impression");
        foreignToEnglish.put("現象", "げんしょう　a phenominom");
        foreignToEnglish.put("組織", "そしき　an organization");
        foreignToEnglish.put("番組", "ばんぐみ　TV program");
        foreignToEnglish.put("価値", "かち　value, worth");
        foreignToEnglish.put("値段", "ねだん　a price");
        foreignToEnglish.put("詰める", "つめる　to stuff in, cram in");
        foreignToEnglish.put("純粋", "じゅんすい　pure");
        foreignToEnglish.put("単純", "たんじゅん　simplistic");
        foreignToEnglish.put("食塩", "しょくえん　table salt");
        foreignToEnglish.put("固形", "こけい　solid (form)");
        foreignToEnglish.put("固定", "こてい　stability, fixation");
        foreignToEnglish.put("菓子", "かし　sweets");
        foreignToEnglish.put("贈り物", "おくりもの　gifts");
        foreignToEnglish.put("省略", "しょうりゃく　abbreviation");
        foreignToEnglish.put("省く", "はぶく　delete, omit");
        foreignToEnglish.put("展示", "てんじ　exhibition, display");
        foreignToEnglish.put("破産", "はさん　bankruptcy (personal)");
        foreignToEnglish.put("倒産", "とうさん　bankruptcy (corporate)");
        foreignToEnglish.put("処理", "しょり　disposal");
        foreignToEnglish.put("処置", "しょち　management measure");
        foreignToEnglish.put("温泉", "おんせん　");
        foreignToEnglish.put("下宿", "げしゅく　lodgings");
        foreignToEnglish.put("季節", "きせつ　season");
        foreignToEnglish.put("豊かな", "ゆたかな　wealthy, abundant");
        foreignToEnglish.put("迎える", "むかえる　go to meet");
        foreignToEnglish.put("送迎", "そうげい　pickup service (for people)");
        foreignToEnglish.put("築～年", "ちく～ねん　built in x year");
        foreignToEnglish.put("三角", "さんかく　triangle");
        foreignToEnglish.put("角度", "かくど　an angle");
        foreignToEnglish.put("徒歩", "とほ　going on foot");
        foreignToEnglish.put("欧米", "おうべい　Europe and America/ the West");
        foreignToEnglish.put("解説", "かいせつ　an explanation");
        foreignToEnglish.put("解決", "かいけつ　a solution");
    }
}
