package com.evansitzes.vocabularyflashcards.model;

/**
 * Created by evan on 9/24/15.
 */
public class ReadingVocabJapanese extends Flashcard {
    @Override
    public void populateInitialWordlist() {
        foreignToEnglish.put("大胆", "(だいたん）Bold, daring, audacious");
        foreignToEnglish.put("成長戦略", "（せいちょうせんりゃく）growth strategy");
        foreignToEnglish.put("目標", "（もくひょう）Objective, target");
        foreignToEnglish.put("策定", "（さくてい）settling on ~");
        foreignToEnglish.put("過程", "（かてい）process, mechanism");
        foreignToEnglish.put("自民党", "（じみんとう）LDP");
        foreignToEnglish.put("柱", "（はしら）pillar (eg. the pillar of support in our economic plan)");
        foreignToEnglish.put("経緯", "（いきさつ）details, particulars, background");
        foreignToEnglish.put("思想的", "（しそうてき）ideally,ideological");
        foreignToEnglish.put("提唱", "（ていしょう）advocacy, proposal");
        foreignToEnglish.put("求める", "（もとめる）to want, request, demand");
        foreignToEnglish.put("代表的", "（だいひょうてき）to be representative of ～");
        foreignToEnglish.put("幅広い", "（はばひろい）broad range");
        foreignToEnglish.put("観点", "（かんてん）point of view");
        foreignToEnglish.put("格付け", "（かくづけ）rating, measuring, assigning");
        foreignToEnglish.put("根源", "（こんげん）source, base, origin");
        foreignToEnglish.put("選挙", "（せんきょ）election");
        foreignToEnglish.put("採用", "（さいよう）used, adopted");
        foreignToEnglish.put("改正", "（かいせい）revision, amendment");
        foreignToEnglish.put("連携", "（れんけい）working together, cooporation");
        foreignToEnglish.put("達成", "（たっせい）accomplishment, attainment, achievment");
        foreignToEnglish.put("および", "(conj) as well as");
        foreignToEnglish.put("創設", "（そうせつ）fouding, establishing");
        foreignToEnglish.put("方策", "（ほうさく）plan, policy");
        foreignToEnglish.put("検討", "（けんとう）deliberate, review, investigate (a course of action)");
        foreignToEnglish.put("もたらす", "(vt) to bring about (eg. changes)");
        foreignToEnglish.put("論者", "（ろんしゃ）advocate");
        foreignToEnglish.put("内閣府", "（ないかくふ）cabinet (govt)");
        foreignToEnglish.put("実施", "（じっし）implementation");
        foreignToEnglish.put("金融", "（きんゆう）financing, financial affairs");
        foreignToEnglish.put("ちらつかせる", "to display, to show off, to flash");
        foreignToEnglish.put("早期退職", "（そうきたいしょく）early retirement");
        foreignToEnglish.put("追い込む", "（おいこむ）to plunge into, force upon, to herd");
        foreignToEnglish.put("大規模", "だいきぼ(large scale)");
        foreignToEnglish.put("唱える", "（となえる）loud, vocal advocation of x");
        foreignToEnglish.put("指名", "（しめい）to point, nominate");
        foreignToEnglish.put("初", "（はつ、うい）first, new");
        foreignToEnglish.put("記者会見", "（きしゃかいけん）press confrence (interview)");
        foreignToEnglish.put("公表", "（こうひょう）official announcement");
        foreignToEnglish.put("量的", "（りょうてき）substantative");
        foreignToEnglish.put("快適", "かいてき　comfortable, agreeable");
        foreignToEnglish.put("丈夫", "じょうぶ　healthy, strong, robust");
        foreignToEnglish.put("実際", "じっさい　in actuality, in fact");
        foreignToEnglish.put("実現", "じつげん　implementation, materialization, make it happen, make it bear fruit");
        foreignToEnglish.put("万一", "まんいち　backup, by chance, in the unlikely event/emergency");
        foreignToEnglish.put("解説", "かいせつ　explenation, commentary");
        foreignToEnglish.put("製造", "せいぞう　manufacturing");
        foreignToEnglish.put("管理方針", "かんりほうしん management policy");
        foreignToEnglish.put("訪問", "ほうもん　a visit");
        foreignToEnglish.put("急速", "きゅうそく(な）　rapid");
        foreignToEnglish.put("主流", "しゅりゅう　commonplace, mainplace");
        foreignToEnglish.put("比率", "ひりつ　ratio, percentage");
        foreignToEnglish.put("古紙", "こし　used/recylced paperq");
        foreignToEnglish.put("順位", "じゅんい　ranking, position");
        foreignToEnglish.put("業務", "ぎょうむ　business affairs");
        foreignToEnglish.put("再資源化", "さいしげんか　recycling, reusing");
        foreignToEnglish.put("と共に", "とともに　in accordance/together with X");
        foreignToEnglish.put("廃棄物", "はいきぶつ　waste matter");
        foreignToEnglish.put("手を加える", "てをくわえる　to revise");
        foreignToEnglish.put("内容", "ないよう　details, comments");
        foreignToEnglish.put("記載", "きさい　record, statement, description");
        foreignToEnglish.put("時とても", "ときとても on some occasions");
        foreignToEnglish.put("提示", "ていじ　presentation, exhibit");
        foreignToEnglish.put("通常", "つうじょう　common, general, normal");
        foreignToEnglish.put("成果", "せいか　fruits (of ones labours), successes");
        foreignToEnglish.put("盛り込む", "もりこむ　to include, incorporate");
        foreignToEnglish.put("大抵", "たいてい　mostly, usually");
        foreignToEnglish.put("提出", "ていしゅつ　to present, to submit (report)");
        foreignToEnglish.put("総収入", "そうしゅうにゅう　total income");
        foreignToEnglish.put("修正", "しゅうせい　amend, modify, fix");
        foreignToEnglish.put("公開", "こうかい　puplic （会社等）");
        foreignToEnglish.put("再び", "ふたたび once again");
        foreignToEnglish.put("追いやる", "おいやる　to drive away, to chase off");
        foreignToEnglish.put("同様に", "どうように　in the exact same way");
        foreignToEnglish.put("世界最大", "せかいさいだい　world's largest");
        foreignToEnglish.put("（を）きっかけに", "with a start in X, taking advantage of X");
        foreignToEnglish.put("親族", "しんぞく　relatives");
        foreignToEnglish.put("店舗", "てんぽ　store, shop");
        foreignToEnglish.put("売却", "ばいきゃく　selling off");
        foreignToEnglish.put("国境", "こっきょう　national boundries");
        foreignToEnglish.put("交換", "こうかん　switching");
        foreignToEnglish.put("長い間", "ながいあいだ　long interval");
        foreignToEnglish.put("政治", "せいじ　politics");
        foreignToEnglish.put("貿易", "ぼうえき　trade");
        foreignToEnglish.put("世紀", "せいき　century, era");
        foreignToEnglish.put("衝撃", "しょうげき　shock, impact, influence");
        foreignToEnglish.put("拡大", "かくだい");
        foreignToEnglish.put("基礎", "きそ　foundation");
        foreignToEnglish.put("一分野", "いちぶんや　one field of study");
        foreignToEnglish.put("扱われ", "あつかわれ　to be treated/handled as x (扱う）");
        foreignToEnglish.put("形成", "けいせい　molding, creating, forming");
        foreignToEnglish.put("理論", "りろん　theory");
        foreignToEnglish.put("予測", "よそく　prediction");
        foreignToEnglish.put("関税", "かんぜい　tariff");
        foreignToEnglish.put("分析", "ぶんせき　analysis");
        foreignToEnglish.put("複数", "ふくすう　multiple");
        foreignToEnglish.put("相対性", "そうたいせい　relativeness （相対的）");
        foreignToEnglish.put("恐らく", "おそらく　likely, probably");
        foreignToEnglish.put("品目", "ひんもく　item, comodity");
        foreignToEnglish.put("特定", "とくてい　specific");
        foreignToEnglish.put("特化", "とっか　specialization");
        foreignToEnglish.put("労働力", "ろうどうりょく　manpower");
        foreignToEnglish.put("資本", "しほん　funds, capital");
        foreignToEnglish.put("割りに", "わりに　comparatively, in proportion");
        foreignToEnglish.put("精度", "せいど　precision, accuracy");
        foreignToEnglish.put("解決", "かいけつ　settlement, resolution");
        foreignToEnglish.put("決定", "けってい　determination");
        foreignToEnglish.put("重点的", "じゅうてんてき　predominant");
        foreignToEnglish.put("欠乏", "けつぼう　want, lack of, shortage, famine");
        foreignToEnglish.put("検証", "けんしょう　inspection, verification");
        foreignToEnglish.put("指摘", "してき　point out, identification");
        foreignToEnglish.put("要素", "ようそ　item, element, factor");
        foreignToEnglish.put("短期間", "たんきかん　short term, short time period, 'minor' time");
        foreignToEnglish.put("重力", "じゅうりょく　gravity");
        foreignToEnglish.put("特徴", "とくちょう　feature, characteristic");
        foreignToEnglish.put("法則", "ほうそく　rule, law");
        foreignToEnglish.put("証明", "しょうめい　proof");
        foreignToEnglish.put("に基づき", "にもとづき　based on x");
        foreignToEnglish.put("手法", "しゅほう　method, technique");
        foreignToEnglish.put("重点", "じゅうてん　important point, stress");
        foreignToEnglish.put("実施項目", "じっしこうもく　working item, point-by-point");
        foreignToEnglish.put("実行", "じっこう　performance, practice, excecution");
        foreignToEnglish.put("診断", "しんだん　evaluation, prognosis");
        foreignToEnglish.put("立案", "りつあん　draft, proposal");
        foreignToEnglish.put("組織", "そしき　organization (ie business, company)");
        foreignToEnglish.put("下位", "かい　subordinate");
        foreignToEnglish.put("展開", "てんかい　develop, progress");
        foreignToEnglish.put("工程不良率", "こうていふりょうりつ　manufacturing defetiveness rate （製造不良率）");
        foreignToEnglish.put("手当てする", "てあてする　to treat, to heal");
        foreignToEnglish.put("手書き", "てがき　by hand");
        foreignToEnglish.put("トランプの手品", "てじな　card tricks");
        foreignToEnglish.put("合計", "ごうけい　the total");
        foreignToEnglish.put("合理的", "ごうりてき　rational, logical");
        foreignToEnglish.put("集合場所", "しゅうごうばしょ meeting place");
        foreignToEnglish.put("合図", "あいず　a signal （送る）");
        foreignToEnglish.put("重体", "じゅうたい　serious injury");
        foreignToEnglish.put("強引", "ごういん（に）　forced to do something");
        foreignToEnglish.put("目安", "めやす　rough estimate");
        foreignToEnglish.put("注目", "ちゅうもく　pay attention to");
        foreignToEnglish.put("気体", "きたい　gas ");
        foreignToEnglish.put("液体", "えきたい　liquid");
        foreignToEnglish.put("固体", "こたい　solid");
        foreignToEnglish.put("事情", "じじょう　circumstances, state of affairs");
        foreignToEnglish.put("相違", "そうい　difference, discrepency ");
        foreignToEnglish.put("強化", "きょうか　strengthen, reinforce");
        foreignToEnglish.put("気に入り", "きにいり　favorite");
        foreignToEnglish.put("面倒", "めんどう　trouble");
    }
}
